### ISSUE TITLE
Power Shutdown - `restart celery workers, acoupi deployment` - Handle items in queues. 

### ISSUE THREAD

**Issue by audevuilli** [acoupi/acoupi#63]
Currently when acoupi program restart after power shutdown, the items inside the queues of rabbitmqctl (celery, recording) are not deleted. This create the `default/celery queue` to be jammed, as too many detections are waiting to be processed. 

- [X] Need to restart `recording` and `default` workers after power shutdown.
- [ ] How to manage previous items in queues? -> unsure yet about deleting them all.

**Comment by mbsantiago** [comment]
Good point, I think it would be good to purge the queues on the start of a deployment. We also need more control over which tasks stay in the queue. Scheduled tasks like recording and heartbeat should be removed since they're time-sensitive and a re-running them later makes no sense. But callback tasks, like detection, must stay in the queue to avoid losing data. Ideally, newer queue messages would have higher priority, and we'd only process pending tasks when the system is idle.

**Comment by mbsantiago** [comment]
I believe we haven't set any task to retry on failure, so this might not be a problem yet. 

But looking at recommendations on celery usage I found this:

1. Set a global task timeout (https://medium.com/@taylorhughes/three-quick-tips-from-two-years-with-celery-c05ff9d7f9eb) 

> By default, tasks don’t time out. If a network connection inside your task hangs indefinitely, your queue will eventually back up and something about your service will mysteriously stop working.
> 
> So you should set some large global default timeout for tasks, and probably some more specific short timeouts on various tasks as well.

While a timeout might cause some recordings or callbacks to be missed, this might not be all that bad. We already track processing status in the metadata DB, so we'd know what was processed or not. However, a timeout on the detection task could lead to recordings stuck in the temporary folder. We might need special handling in the file management task to address this.
